sudo: required
addons:
  firefox: "latest"
  apt:
    packages:
      - google-chrome-stable

language: node_js

node_js:
  - "10"

before_script:
  - npm install
  - npm run start &

script:
  - npm run e2e